### ISSUE TITLE
Tappy is Advertising

### ISSUE THREAD

**Issue by ghost** [PinoyLifeCraft/Report-Player-Abuse-Forums#1]
She is Advertising In PLC Server staffs ban ip nyo daw po sya ang sabi nya I got Evidens LoL_isTappy is Advertising

**Comment by PinoyLifeCraft** [comment]
Hello there @xXDragonGBAxX15,

Thank You for your concern or care, but it seems you don't have an evidence we need your proof to proceed your to your report. Picture , ScreenShot or even video , Thank You.

**Comment by pinoylifecraft** [comment]
Hello there @xXDragonGBAxX15,

Thank you for your concern and care, one of the staffs in the team was a witness and give him a 2-3day temporary ban. You need not to worry because a staff already took care of the case.

Best Regards,
GM : MineCraftJohn
Pinoy LifeCraft GameMaster
