### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by HenryBruno-Mars** [PinoyLifeCraft/Report-Player-Abuse-Forums#4]
![image](https://user-images.githubusercontent.com/33455406/32854949-1df779fa-c9f5-11e7-9ea9-ec2f10a4ae71.png)

Having connection problems 3 days now, everytime i die can't re spawn and reconnect as will

**Comment by pinoylifecraft** [comment]
Hello there Henry,

It seems spigot 1.12.2 is not compatible yet and has lots of bugs for now so this issue has been fixed already, we've downgrade our server version to compatible version (1.12.1
)

**Comment by HenryBruno-Mars** [comment]
Thank you guys!

- PinoyLifeCraft Admin: HenryBruno_Mars
